server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server

 # server:
  #  enable-self-preservation: false #简单粗暴把自我保护模式关闭 更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
    #eviction-interval-timer-in-ms: 4000 # 清理间隔（单位毫秒，默认是60*1000）



#---
#spring:
#  profiles: server1
#  application:
#    name: eurka-server
#server:
#  port: 8780
#eureka:
#  instance:
#    hostname: server1
#  client:
#    serviceUrl:
#      defaultZone: http://server2:8769/eureka/
#
#---
#spring:
#  profiles: server2
#  application:
#    name: eurka-server
#server:
#  port: 8769
#eureka:
#  instance:
#    hostname: server2
#  client:
#    serviceUrl:
#      defaultZone: http://server1:8780/eureka/



