server:
  port: 8763
spring:
  application:
    name: consul-provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enable: true
      discovery:
        enable: true
        #        serviceName: consul-provider
        #        ip-address: 127.0.0.1
#        prefer-ip-address: true
        #        health-check-url: http://${spring.cloud.consul.discovery.ip-address}:${server.port}//health
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #实例ID
        health-check-path: /actuator/health   #健康检查
        health-check-interval: 20s