server:
  port: 9527

nacos:
  config: public

spring:
  application:
    name: nacos-provide
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #  security:
#    user:
#      name: zp
#      password: b
  boot:
    admin:
      client:
        url: http://localhost:8000
#        username: admin
#        password: admin
#        instance:
#          name: ${spring.application.name}
#          metadata: # 这个name与password用于在注册到管理端时，使管理端有权限获取客户端端点数据
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1 #抓取100%的日志 默认0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  # 展示endpoint细节信息  细节信息，包括磁盘、cpu、内存使用情况
  endpoint:
    health:
      show-details: ALWAYS

info:
  app: nacos-provide-demo

