#server:
#  port: 9527

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8090
#      datasource:
#        ds:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-sentinel
#            groupId: DEFAULT_GROUP
#            ruleType: flow
            # 以上属性可查看NacosDataSourceProperties 和 DataSourcePropertiesConfiguration 该类