
server:
  port: 9411

spring:
  application:
    name: nacos-sleuth-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 关闭自动配置启用所有请求得检测
management:
  metrics:
    web:
      server:
        auto-time-requests: false # 关闭自动配置启用所有请求得检测
#  security:
#    enabled: false #关闭验证
#info: #/info请求的显示信息
#  app:
#    name: ${spring.application.name}
#    version: 1.0.0
#  build:
#    artifactId: @project.artifactId@
#    version: @project.version@


zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1
      port: 5672
      username: guest
      password: guest
#      virtual-host: vh1
      queue: zipkin
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      hosts: 127.0.0.1:9200
      cluster: elasticsearch
      index: zipkin
      index-shards: 5
      index-replicas: 1