server:
  port: 8771

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/954480192/test
          username: 954480192@qq.com
          password: 265628ad

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/