server:
  port: 8771

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/954480192/test
#          username: 954480192@qq.com
#          password: 265628ad
#          searchPaths：
#      label：
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 允许/actuator/bus-refresh接口被外部调用
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh